ALTER TABLE transactions ADD COLUMN IF NOT EXISTS is_future BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED';
ALTER TABLE transactions ADD CONSTRAINT transactions_status_check CHECK (status IN ('PENDING', 'CONFIRMED'));